// final List<String> keywords = [
//   "hello",
//   "how are you",
//   "good morning",
//   "good afternoon",
//   "good evening",
//   "bye",
//   "thanks",
//   "help",
//   "problem",
//   "yes",
//   "no",
//   "please",
//   "information",
//   "what's your name",
//   "tell me a joke",
//   "how old are you",
//   "where you from",
//   "what do you do",
//   "who created you",
//   "are you a human",
//   "what's the weather like",
//   "what's your favorite color",
//   "what's the meaning of life",
//   "can you dance",
//   "do you have any siblings",
//   "what's your favorite food",
//   "what's your favorite movie",
//   "do you dream",
//   "what's the time",
//   "what's the date",
//   "do you love me",
//   "how can I contact you",
//   "are you smart",
//   "are you alive",
//   "do you know any languages",
//   "do you have a pet",
//   "can you sing",
//   "can you draw",
//   "can you cook",
//   "do you play games",
//   "what's your favorite book",
//   "what's your favorite song",
//   "can you tell a bedtime story",
//   "what's the capital of [country]",
//   "how can I learn programming",
//   "what's the latest news",
//   "what's the meaning of [word]",
//   "can you help me with my homework",
//   "can you recommend a restaurant",
//   "what's your favorite sport",
//   "what's your favorite animal",
//   "do you have any hobbies",
//   "are you feeling well",
//   "do you believe in aliens",
//   "what's your favorite place",
//   "are you a bot",
//   "can you solve math problems",
//   "what's your favorite subject",
//   "do you like to travel",
//   "what's the meaning of love",
//   "can you speak [language]",
//   "can you tell a riddle",
//   "what's the best movie ever",
//   "can you do magic",
//   "what's your favorite emoji",
//   "what's your favorite song",
//   "what's your favorite holiday",
//   "what's your favorite season",
//   "can you tell me a story",
//   "what's your favorite instrument",
//   "what's your favorite game",
//   "do you have a job",
//   "what's your favorite quote",
//   "do you believe in ghosts",
//   "what's your favorite TV show",
//   "what's your favorite superhero",
//   "do you like to exercise",
//   "what's your favorite app",
//   "do you have a favorite number",
//   "what's the best way to relax",
//   "what's your favorite drink",
//   "do you have any fears",
//   "can you tell me a fun fact",
//   "what's your favorite dessert",
//   "what's the meaning of happiness",
//   "what's the meaning of success",
//   "do you like to read",
//   "what's your favorite flower",
//   "can you tell me a poem",
//   "what's your favorite planet",
//   "what's your favorite constellation",
//   "what's your favorite element",
//   "can you tell me a secret",
//   "what's the secret of life",
//   "what's your favorite landmark",
//   "do you have any pets",
//   "what's your favorite hairstyle",
//   "do you like to dance",
//   "what's your favorite hobby",
//   "can you tell me a joke",
//   "what's your favorite language",
//   "what's your favorite invention",
//   "can you tell me a fact",
//   "what's your favorite website",
//   "what's the best advice you can give",
//   "do you like music",
//   "who are you",
//   "who is iksoft original",
//   "how can i contact him",
//   "contact"
// ];
