// final List<String> responses = [
//   "Hello! \nWelcome to IkBot\nHow can I assist you?",
//   "I'm just a bot, but I'm here to help!",
//   "Good morning! How can I be of service?",
//   "Good afternoon! How can I assist you today?",
//   "Good evening! How can I help you?",
//   "Goodbye! Have a great day!",
//   "You're welcome!",
//   "I'm here to help. What do you need assistance with?",
//   "I'm sorry to hear that. Can you provide more details?",
//   "Yes, I understand.",
//   "No, I'm sorry, I don't understand.",
//   "Sure, please provide more information.",
//   "Sure, here is the information you requested.",
//   "My name is ChatBot.",
//   "Sure! Why don't scientists trust atoms? Because they make up everything!",
//   "I don't have an age, I'm just a program.",
//   "I exist in the virtual world.",
//   "I'm a chatbot designed to assist with various tasks.",
//   "I was created by OpenAI.",
//   "I'm a virtual assistant, not a human.",
//   "I can't provide real-time weather updates.",
//   "I don't have preferences like humans do.",
//   "The meaning of life is a philosophical question.",
//   "I'm not equipped to dance.",
//   "I'm a virtual assistant, so I don't have siblings.",
//   "I don't eat, but I can suggest recipes!",
//   "I don't watch movies, but I can recommend some.",
//   "I don't experience dreams as humans do.",
//   "I don't have a physical form, so I don't perceive time.",
//   "I can't provide real-time dates.",
//   "I'm just a program, so I don't have feelings.",
//   "I'm here to assist you in this chat.",
//   "I don't have consciousness or emotions.",
//   "I can communicate in various languages.",
//   "I don't have physical senses.",
//   "I can't cook, but I can suggest recipes!",
//   "I can't play games, but I can recommend some.",
//   "I don't read, but I have access to a vast database.",
//   "I don't have preferences like humans do.",
//   "I don't have personal experiences or emotions.",
//   "I can't sing, but I can provide lyrics!",
//   "I can't draw, but I can suggest artistic ideas.",
//   "I can't cook, but I can suggest recipes!",
//   "I can't play games, but I can suggest some to you.",
//   "I don't have personal preferences.",
//   "I don't experience time, so I don't know the latest news.",
//   "I can provide definitions for words.",
//   "I can assist with various subjects.",
//   "I can recommend restaurants based on your location.",
//   "I don't have preferences like humans do.",
//   "I'm just a program, so I don't experience emotions.",
//   "I can provide information about different sports.",
//   "I don't have preferences like humans do.",
//   "I'm here to assist you, not to express feelings.",
//   "I'm just a program, so I don't have personal experiences.",
//   "I'm designed to assist with various tasks.",
//   "I don't have personal experiences or emotions.",
//   "I'm a virtual assistant, not a human.",
//   "I can solve math problems, but I don't have consciousness.",
//   "I can assist with a wide range of subjects.",
//   "I'm not capable of traveling.",
//   "The meaning of love can vary for different people.",
//   "I can communicate in various languages.",
//   "Sure, here's a riddle for you: What has keys but can't open locks? A piano!",
//   "That's subjective, but many people love 'The Shawshank Redemption.'",
//   "I don't have magical abilities.",
//   "I can't see, but I can describe emojis!",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't experience seasons or weather.",
//   "I can tell you a story! Once upon a time...",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal experiences or emotions.",
//   "I don't experience emotions, so I can't define happiness.",
//   "Success can mean different things to different people.",
//   "I don't experience emotions, so I can't have preferences.",
//   "I don't have personal preferences.",
//   "I can tell you a poem! Roses are red...",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences."
//       "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I don't have personal preferences.",
//   "I am IkChatBot created by Iksoft Technologies",
//   "Iksoft Original is a professional Software Engineer and a media Expert in all aspects who always work on time and meet clients expectations .My name is Adu Amankwah Isaac , CEO of Iksoft Technologies and Technical supervisor for a lot of TV Stations .Am Known in the Tech Industry as Iksoft Original . He have 9 years Work experience as a media personnel and 5 years experience as a Developer . He have worked with Great Companies Both Locally and Internationally. He is a professional Software Engineer and a media Expert in all aspects who always work on time and meet clients expectations .My name is Adu Amankwah Isaac , CEO of Iksoft Technologies and Technical supervisor for a lot of TV Stations .He is Known in the Tech Industry as Iksoft Original . He has 9 years Work experience as a media personnel and 5 years experience as a Developer . He have worked with Great Companies Both Locally and Internationally.",
//   "Contact him on +233 550 138 086 / +233 543 261 734\nMail: info@afrilen.com\nYouTube Channel: IkeTech in Twi & IkeTech Channel",
//   "Contact him on +233 550 138 086 / +233 543 261 734\nMail: info@afrilen.com\nYouTube Channel: IkeTech in Twi & IkeTech Channel"
// ];
